[package]
name = "orb"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
rayon = "1.8"